### PR TITLE
Fixed missing source file assets on some samples

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR fixes an issue where the `.xaml` and `.cs` source files were failing to load in-app for some samples.

Related #18

### CODE REVIEW

**Comment by Arlodotexe** [comment]
This has been tested on UWP and Wasm. Wasdk still needs testing, I ran into issues getting it to launch on my machine.

**Comment by michael-hawker** [comment]
That fixed the Headered control ones, but the behaviors are still broken:

image

Probably because they're in a sub-directory for organization:

image

(Same with the ConstrainedBox samples.)

Suppose we should just flatten them for now? 😟 Would be nice to support folders for samples as Behaviors, Primitives, the Extensions are all larger projects.

Is there a better way we can think to test and validate this setup moving forward too?

**Comment by Arlodotexe** [comment]
I guess we just flatten them for now. There's not many options in terms of finding the subfolder path of a xaml or cs file, and we're on a tight schedule.

**Comment by michael-hawker** [comment]
Had a thought during lunch and came to a realization why this `folderpath` was there.

There's a couple of issues with different causes:
1. The Headered control samples are using `HeaderedContentControlExperiment.Samples` namespace, but it should be `HeaderedControlsExperiment.Samples` instead as we trim the assembly name from the path here:

    https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/b8e7235a29ac26a63745a4aafbb04417e671536b/CommunityToolkit.App.Shared/Renderers/ToolkitSampleRenderer.xaml.cs#L267
    
    Since they don't match, that was causing these ones not to load.

2. Since we use the namespace as an identifier and replace `.` with `/` above...

    https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/b8e7235a29ac26a63745a4aafbb04417e671536b/CommunityToolkit.App.Shared/Renderers/ToolkitSampleRenderer.xaml.cs#L255

   If the Behaviors and the ConstrainedBox samples in theirs sub-folders added the folder name to the namespace (as VS usually tries to do) instead of being in a flattened root namespace, then it should be able to properly load the samples (assuming our SG doesn't care about namespace...)

Going to test this out now by adjusting the namespaces of these three sets of samples.

**Comment by michael-hawker** [comment]
Fixed in https://github.com/CommunityToolkit/Windows/pull/214 now! 🎉🎉🎉

No tooling changes required, going to close this.

**Pull request closed without merging**
