### PR TITLE
Update Uno version, Uno TFMs to .NET 8

### LINKED ISSUE #182: Update Uno Platform library TFMs to net8.0
## Background

Our Uno Platform TFMs are currently set to `net7.0*`, originally upgraded in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/117.

## The problem

However, .NET 7 will [reach End of Support](https://devblogs.microsoft.com/dotnet/dotnet-7-end-of-support/) on May 14, 2024.

## The solution

Since .NET 8 is an LTS release and will be supported until November 10, 2026, we should aim to onboard our users to this version _before_ .NET 7 hits end of support, and (far) before .NET 9 is released. 

People can take a long time to update their projects, so we should prefer targeting LTS instead of STS when LTS is newer. The sooner we onboard consumers to the newest LTS, the healthier the ecosystem in the long term.

## Additional info

See the official [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#release-types) for details and guidance.

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR:
- Updates our Uno packages to the latest stable version
- Closes #182. Updates the TFMs that Uno runs on from net7.0 to net8.0
- Fixes any issues that arise from the move to net8.0

### CODE REVIEW

**Review by Arlodotexe — COMMENTED** [review]
Opened as a draft. We're seeing linker issues when compiling release mode. Tested against the [main repo](https://github.com/CommunityToolkit/Windows) by running this command:
```
.\tooling\Build-Toolkit-Gallery.ps1 -Head wasm -MultiTargets wasm -Components All -WinUIMajorVersion 2 -Release
```
We see this error message:
```
C:\Users\arlog\.nuget\packages\uno.wasm.bootstrap\7.0.29\build\Uno.Wasm.Bootstrap.targets(206,3): error : System.Exception: Failed to exe 
       cute the linker [C:\Users\arlog\source\repos\Windows\tooling\ProjectHeads\AllComponents\wasm\CommunityToolkit.App.Wasm.csproj]
```

**Comment by Arlodotexe** [comment]
Thanks @jeromelaban for the help!

For reference, the issue was that the `Uno.Wasm.Bootstrap` package version doesn't align with Uno.UI/Uno.WinUI/etc. via our `CommonUnoPackageVersion` property and had to be updated separately. We'll need to keep this in mind for future updates. Unfortunately, we can't make use of the [Uno SDK](https://platform.uno/docs/articles/features/using-the-uno-sdk.html?tabs=uno-packages) to keep things in step because it doesn't support UWP. 

We should be able to close this off and include the changes in the 8.1 update.

**Review by michael-hawker — APPROVED** [review]

**Comment by michael-hawker** [comment]
May want to look at the 422 equivalent as there's an Android error there:

```
error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Ref.33' was not present in workload manifests. [C:\a\Windows\Windows\components\Triggers\samples\Triggers.Samples.csproj::TargetFramework=net8.0-android33.0]
```

**Comment by jeromelaban** [comment]
> May want to look at the 422 equivalent as there's an Android error there:

This generally happens when the TargetPlatformVersion is 33 instead of 34 (which net8 targets).

**Comment by Arlodotexe** [comment]
Thanks Jerome, I'll give that a try. Found additional information on this error message [here](https://github.com/xamarin/xamarin-android/issues/8331).

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
