### PR TITLE
Disable consolelogger, add tracking issue

### PR DESCRIPTION
**Pull request by Arlodotexe**
Disabled consolelogger in our solution generation script to avoid https://github.com/microsoft/slngen/issues/451 until it is fixed

### CODE REVIEW

**Review by michael-hawker — APPROVED** [review]

**Comment by Arlodotexe** [comment]
Looks like testspace got stuck, I'll rerun

**Comment by michael-hawker** [comment]
Yeah, I'm not too sure what's going on. It's like its saying the number of tests are different, which is weird with this type of change. But I do see the numbers being different, but not sure why that is the case... (number of test cases run)

**Comment by michael-hawker** [comment]
Closing to kick off fresh build...?

**Comment by michael-hawker** [comment]
Sending mail to testspace to get more, but this seems to be an issue with how the test logs are being uploaded and bucketed, everything is passing in the CI. Going to merge this and follow-up with them.

**Pull request merged**
