### PR TITLE
Update build.yml to test including process dumps

### PR DESCRIPTION
**Pull request by michael-hawker**
Needed to help diagnose issue https://github.com/CommunityToolkit/Windows/issues/347

built-off AOT `wasdk/1.6` branch, as suspect we've seen an uptick with this issue with 1.6 over 1.5, but it's also more finicky in PR build over integration builds, which is also weird.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Oh, I hadn't noticed you manually changed the base branch. I'll revert my change.

**Comment by michael-hawker** [comment]
> Oh, I hadn't noticed you manually changed the base branch. I'll revert my change.

Yeah, I don't think it wouldn't run the CI if I was just targeting your branch, I just wanted to test against the latest WASDK, so grabbed your branch as a starting point. 😊

Don't intend to merge this PR, just use it to collect dumps, and if that works can clean-it up later, but at least want to get dumps to provide platform team to see if they can assist us in understanding what's happening, if we can't.

**Comment by michael-hawker** [comment]
Hitting https://github.com/microsoft/slngen/issues/451 when turning diagnostics on, so will turn slngen flag carrying that over.

**Comment by Arlodotexe** [comment]
Migrating to https://github.com/CommunityToolkit/Windows/pull/493

**Pull request closed without merging**
