### PR TITLE
Updated default sample icon

### LINKED ISSUE #151: Better default Icon / Replace Box icons for components
Image

Need to replace this default, and update ones using it

### PR DESCRIPTION
**Pull request by Arlodotexe**
Closes #151

### CODE REVIEW

**Comment by michael-hawker** [comment]
@niels9001 this look good to you? @Arlodotexe how does it look in the sample app compared to the other icons?

**Comment by niels9001** [comment]
@Arlodotexe @michael-hawker I've created a new placeholder icon that you can use (it's also 54px instead of 74px)

Placeholder




Put in a PR for updating the Labs components here: https://github.com/CommunityToolkit/Labs-Windows/pull/510

**Comment by Arlodotexe** [comment]
> @niels9001 this look good to you? @Arlodotexe how does it look in the sample app compared to the other icons?

Looks good, should be ready to close 

image

**Comment by Arlodotexe** [comment]
@michael-hawker Needs an approving review

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
