### PR TITLE
feat: Bump to Uno 5.x

### PR DESCRIPTION
**Pull request by MartinZikmund**
Related to https://github.com/CommunityToolkit/Windows/issues/281

Bump Uno Platform target version to 5.0.48

### CODE REVIEW

**Comment by giraudremy** [comment]
I have similar issue with v8.0 : System.MissingMethodException: Method not found: double Microsoft.UI.Xaml.Thickness.get_Left()
[https://github.com/CommunityToolkit/Windows/discussions/278](url)

**Comment by MartinZikmund** [comment]
> I have similar issue with v8.0 : System.MissingMethodException: Method not found: double Microsoft.UI.Xaml.Thickness.get_Left()
> [https://github.com/CommunityToolkit/Windows/discussions/278](url)

Should fix that as well

**Comment by michael-hawker** [comment]
@MartinZikmund is there a way to fix this for both Uno 4.x and 5.x users instead?

Or are you seeing most Uno 4.x folks upgrade to 5 right away? Just concerned with forcing folks to have to update when taking toolkit packages.

Looks like there's more beyond just a version bump that's needed here too. 😅

**Comment by MartinZikmund** [comment]
I think it is safe to upgrade as most people upgrade right away (as there is a lot of new features), plus all the first party libraries are updated to 5.x right away too, so if you want to use the latest of anything, then updating to 5.x and later is the only option.

**Comment by michael-hawker** [comment]
@MartinZikmund you still planning to take a look at the failures or need assistance? We're tentatively hoping to do an update in a couple weeks once we resolve some other issues as well, so we could work this one in.

**Comment by MartinZikmund** [comment]
@michael-hawker can you please run the workflows again? I rebased and didn't realize I would not see the build failures then anymore :-( ...

**Comment by michael-hawker** [comment]
@MartinZikmund no worries, rekicked, though if you go to the main Actions tab you should be able to find the old build, think this was it:
https://github.com/CommunityToolkit/Tooling-Windows-Submodule/actions/runs/7022761057

**Comment by MartinZikmund** [comment]
Created https://github.com/unoplatform/uno/pull/14759 which should fix the build issue, will rebase on that update of Uno after it is merged

**Comment by MartinZikmund** [comment]
Still the same, trying the latest to see whether the backport was not successful somehow, can you please run the workflow?

**Comment by MartinZikmund** [comment]
@Arlodotexe let's try again

**Comment by Arlodotexe** [comment]
@MartinZikmund The CI is passing for the submodule, but when building the Wasm head in the `CommunityToolkit/Windows` or `CommunityToolkit/Labs-Windows` repo, I'm getting errors such as
```
CSC : error UXAML0001: The type x:String could not be found [D:\source\uwp\lib\Windows\components\Converters\sam
       ples\Converters.Samples.csproj::TargetFramework=net7.0]
```

I've opened a PR [here](https://github.com/CommunityToolkit/Windows/pull/311) so we can see the errors coming from toolkit components in the CI.

**Comment by MartinZikmund** [comment]
@Arlodotexe new update is in, now including the https://github.com/unoplatform/uno/pull/15155 fix

**Comment by michael-hawker** [comment]
Thanks @MartinZikmund, I kicked off the CI. @Arlodotexe you going to update the dependent PR on the main repo?

**Review by Arlodotexe — APPROVED** [review]
All green in https://github.com/CommunityToolkit/Windows/pull/311, let's merge

**Pull request merged**
