### PR TITLE
Fix #215 - Extra webview2 dll in nuget package

### LINKED ISSUE #215: NuGet validation fails with 1.6 references due to unexpected included webview2loader.dll
Got a report from building with 1.6-stable against our latest 1.6-preview2 bits with this error:

1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5321,5): error MSB3030: Could not copy the file "C:\Users....nuget\packages\communitytoolkit.winui.animations\8.2.240909-build.1181\lib\net8.0-windows10.0.22621\CommunityToolkit.WinUI.Animations\runtimes\win-x64\native\WebView2Loader.dll" because it was not found.

looks like a path problem:
 
Wrong
C:\Users....nuget\packages\communitytoolkit.winui.animations\8.2.240909-build.1181\lib\net8.0-windows10.0.22621\CommunityToolkit.WinUI.Animations\runtimes\win-x64\native\
 
Correct
C:\Users....nuget\packages\communitytoolkit.winui.animations\8.2.240909-build.1181\lib\net8.0-windows10.0.22621.0\CommunityToolkit.WinUI.Animations\runtimes\win-x64\native
Note the missing `.0` in the TFM part of the path, should be `net8.0-windows10.0.22621.0` but was `net8.0-windows10.0.22621`.

Talking with @Arlodotexe it sounds similar (though different) to the issue Morten had reported in Labs here: https://github.com/CommunityToolkit/Labs-Windows/pull/569

Though with all the WebView changes between preview1 and stable, we may just want to have them reproduce once we have a 1.6 build to try. Still an issue in 1.6 stable, seems like a regression in the platform.

_Originally posted by @michael-hawker in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/205#issuecomment-2339279747_ - [Internal Platform Tracking Issue](https://microsoft.visualstudio.com/OS/_workitems/edit/53865998)

### PR DESCRIPTION
**Pull request by michael-hawker**
Remove webview2loader.dll from package (hopefully) - test workaround to report back to platform.

Fixes #215 

Going to open a Windows PR using this to see if it resolves the issue or not.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
> _Reposting https://github.com/CommunityToolkit/Windows/pull/521#issuecomment-2374680572_

I've managed to fix the issue. It took a combination of updating WebView2 (as per @Sergio0694's suggestion) and removing both conditions around `WebView2NeverCopyLoaderDllToOutputDirectory`. Leaving either condition would result in broken packages again, but with both removed and webview2 updated:

image

This seems to have also resolved the issue with the extra `net8.0-windows10.0.22621.0` TFM being included alongside `net8.0-windows10.0.22621`.

**Review by Arlodotexe — APPROVED** [review]

**Comment by beeradmoore** [comment]
@Arlodotexe , I was previously using `CommunityToolkit.Labs.WinUI.MarkdownTextBlock`, but all of a sudden I am having a bunch of issues about copying the webview 2 dll. Going down the rabbit hole led me here. 

From what I can understand we are waiting for things to be merged and pushed to labs preview feed?

Is there any way to fix this in our application in the meantime? I have tried adding WebView2 nuget, as well as differnet combinations of with/without/with different values of `WebView2NeverCopyLoaderDllToOutputDirectory` but nothing seems to fix it.

**Comment by michael-hawker** [comment]
@beeradmoore this should be fixed in the latest labs packages, as the tooling PR was updated in Labs here: https://github.com/CommunityToolkit/Labs-Windows/pull/574

FYI @Arlodotexe

**Comment by beeradmoore** [comment]
Hey @michael-hawker , confirming this appears to be fixed.

I nuked my nuget packages cache and updated to `0.1.241029-build.1770` and it now builds fine. Formatting is still way off when showing markdown compared to where it came from pre-labs, but at least the project builds now without workarounds.

**Comment by michael-hawker** [comment]
Thanks for confirming @beeradmoore! 🦙❤️ Yeah, there's definitely still a gap from where the old control was to this new one. The big advantage here to the new one is that it's no longer built on a bespoke custom-built parser underneath.

Feel free to submit any fixes you find for anything, happy to take contributions!

**Pull request merged**
